# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Read Options from File
      id: read-options
      run: |
        options=$(cat options.txt)
        echo "::set-output name=options::$options"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  
  prompt:
    needs: options
    runs-on: ubuntu-latest
    steps:
      - name: Choose Option
        id: prompt
        uses: actions/github-script@v4
        with:
          script: |
            const options = '${{ needs.build.outputs.options }}'.split('\n');
            const choice = await github.prompt("Select an option:", options);
            console.log(choice);
